import { type JSX, useEffect, useState } from "react";
import { createHighlighterCore, type HighlighterCore } from "shiki/core";
import { createOnigurumaEngine } from "shiki/engine/oniguruma";

// Cache the highlighter instance because it is expensive to create.
// https://shiki.style/guide/bundles#fine-grained-bundle
// https://shiki.style/guide/best-performance#cache-the-highlighter-instance
// Ref: https://github.com/cloudflare/vinext/blob/ee551d1e28a88df762c7b8e95ebbecf21b45267f/apps/web/app/page.tsx#L177-L199
let highlighterPromise: ReturnType<typeof createHighlighterCore> | null = null;

function getHighlighter(): Promise<HighlighterCore> {
  highlighterPromise ??= createHighlighterCore({
    themes: [import("@shikijs/themes/github-light")],
    langs: [import("@shikijs/langs/bibtex"), import("@shikijs/langs/json")],
    engine: createOnigurumaEngine(import("shiki/wasm")),
  });
  return highlighterPromise;
}

export function SyntaxHighlighter({
  language,
  children,
  className,
}: {
  language: "bibtex" | "json" | "text";
  children: string;
  className?: string;
}): JSX.Element {
  const [html, setHtml] = useState<string>("");

  useEffect(() => {
    let cancelled = false;

    (async () => {
      // This is a workaround to use async/await in client components.
      const highlighter = await getHighlighter();
      const highlightedCode = highlighter.codeToHtml(children, {
        lang: language,
        theme: "github-light",
      });
      if (!cancelled) {
        setHtml(highlightedCode);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [language, children]);

  return (
    <div className="syntax-highlighter">
      <div
        className={className}
        // biome-ignore lint/security/noDangerouslySetInnerHtml: Trust the html generated by shiki
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </div>
  );
}
