name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-processors:
    runs-on: ubuntu-latest
    env:
      # 有文献包含日文汉字，中易和思源支持，而 Fandol 缺字。故 Ubuntu 上编译 LaTeX 需从 Fandol 切换到思源
      CTEX_FONTSET: ubuntu

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: typst-community/setup-typst@v5
        with:
          typst-version: v0.14
      - uses: hustcer/setup-nu@v3
        with:
          version: "0.113.1"

      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - run: pnpm install
        working-directory: processors/zotero

      - uses: astral-sh/setup-uv@v8.2.0
      - run: uv sync
        working-directory: processors/typst_etc

      - uses: zauguin/install-texlive@v4
        with:
          texlive_version: 2026
          package_file: .github/tl_packages
      - name: Install pdftotext and Noto CJK fontset
        # This step is unnecessary for Windows because of `tlmgr install wintools.windows` and `fontset=windows`.
        run: |
          sudo apt update
          sudo apt install poppler-utils fonts-noto-cjk

      - run: nu scripts/setup-style-cache.nu
      - run: nu scripts/setup-typst-local-pkg.nu

      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.builtin.json
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.better.json
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.builtin.bib
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.better.bib
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.original.toml

      - uses: actions/upload-artifact@v7
        with:
          name: target-out
          path: target/out/

  build-website:
    runs-on: ubuntu-latest
    needs: run-processors
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/download-artifact@v8
        with:
          name: target-out
          path: target/out/

      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - run: pnpm install
        working-directory: website

      - run: pnpm test
        working-directory: website
      - run: pnpm fmt
        working-directory: website
      - run: pnpm typecheck
        working-directory: website
      - run: pnpm build
        working-directory: website

      - uses: actions/upload-artifact@v7
        with:
          name: website-build-client
          path: website/build/client/

  deploy-netlify:
    runs-on: ubuntu-latest
    needs: build-website
    environment:
      name: deploy-netlify
      url: ${{ steps.netlify-deploy.outputs.deploy_url }}
    steps:
      - uses: actions/checkout@v6
      - run: mkdir -p website/build/
      - uses: actions/download-artifact@v8
        with:
          name: website-build-client
          path: website/build/client/
      - name: Install netlify-cli
        run: npm install -g netlify-cli@^26.1.0
      - name: Run netlify deploy ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
        id: netlify-deploy
        shell: bash
        run: |
          set -euxo pipefail
          netlify deploy \
            --dir website/build/client/ \
            --message "Deployed from $(git describe --dirty --always) (run ${{ github.run_id }} by ${{ github.triggering_actor }} from ${{ github.ref }} in ${{ github.repository }})" \
            ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} \
            --no-build \
            --json \
            --debug | tee netlify-deploy.log
          cat netlify-deploy.log

          deploy_url=$(cat netlify-deploy.log | grep --invert-match '^\[project.\ts\]: detect' | jq .deploy_url --raw-output)
          echo "deploy_url=$deploy_url" >> "$GITHUB_OUTPUT"
        env:
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
