name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      release:
        description: Whether to publish artifacts in a new release.
        default: false
        type: boolean

permissions:
  contents: read

jobs:
  run-processors:
    runs-on: ubuntu-latest
    env:
      # 有文献包含日文汉字，中易和思源支持，而 Fandol 缺字。故 Ubuntu 上编译 LaTeX 需从 Fandol 切换到思源
      CTEX_FONTSET: ubuntu

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: typst-community/setup-typst@v5
        with:
          # Required by setup-typst-local-pkg.nu.
          # NOTE: Sync the typst version with typst_etc/pyproject.toml.
          typst-version: v0.15
      - uses: hustcer/setup-nu@v3
        with:
          version: "0.113.1"
      - uses: taiki-e/install-action@v2
        with:
          tool: ripgrep
      - name: Setup pandoc
        shell: bash
        run: |
          set -euxo pipefail
          curl -LO https://github.com/jgm/pandoc/releases/download/3.10/pandoc-3.10-linux-amd64.tar.gz
          tar xvf pandoc-3.10-linux-amd64.tar.gz
          mkdir -p ~/.local/bin/
          mv pandoc-3.10/bin/pandoc ~/.local/bin/
          rm -rf pandoc-3.10-linux-amd64.tar.gz pandoc-3.10/
          pandoc --version

      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - run: pnpm install
        working-directory: processors/zotero

      - uses: astral-sh/setup-uv@v8.2.0
      - run: uv sync
        working-directory: processors/typst_etc

      - uses: zauguin/install-texlive@v4
        with:
          texlive_version: 2026
          package_file: .github/tl_packages
      - name: Install pdftotext and Noto CJK fontset
        # This step is unnecessary for Windows because of `tlmgr install wintools.windows` and `fontset=windows`.
        run: |
          sudo apt update
          sudo apt install poppler-utils fonts-noto-cjk

      - run: nu scripts/setup-style-cache.nu
      - run: nu scripts/setup-typst-local-pkg.nu

      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.builtin.json
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.better.json
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.builtin.bib
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.better.bib
      - run: nu scripts/run-processors.nu data/data/GB-T_7714—2025.original.toml

      - uses: actions/upload-artifact@v7
        with:
          name: target-out
          path: target/out/

      - name: Collect versions of LaTeX processors
        if: ${{ always() }}
        run: |
          nu scripts/collect-tex-versions.nu > tex-versions.yaml

          echo '```yaml' >> "$GITHUB_STEP_SUMMARY"
          cat tex-versions.yaml >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"
      - uses: actions/upload-artifact@v7
        with:
          path: tex-versions.yaml
          archive: false

  release:
    runs-on: ubuntu-latest
    needs: run-processors
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.release || false }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v8
        with:
          name: target-out
          path: target/out/
      - uses: actions/download-artifact@v8
        with:
          name: tex-versions.yaml

      - name: Prepare for the release
        id: prepare
        shell: bash
        run: |
          set -euxo pipefail
          cd target/
          7z a ../target-out.zip out/
          cd -

          echo "commit_date=$(git log -1 --format=%cd --date=format:%Y-%m-%d)" >> "$GITHUB_OUTPUT"
          echo "data_revision=$(git rev-parse HEAD:data)" >> "$GITHUB_OUTPUT"
          {
            echo 'tex_versions<<EOF'
            cat tex-versions.yaml
            echo EOF
          } >> "$GITHUB_OUTPUT"

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.prepare.outputs.commit_date }}
          name: ${{ steps.prepare.outputs.commit_date }}
          body: |
            数据源版本：https://github.com/typst-doc-cn/bib-csl-dev-data/tree/${{ steps.prepare.outputs.data_revision }}

            LaTeX 系列引擎的版本：

            ```yaml
            # tex-versions.yaml
            ${{ steps.prepare.outputs.tex_versions }}
            ```

            其它引擎的版本见源代码。
          draft: true
          prerelease: false # can be edited in the Web UI
          files: |
            tex-versions.yaml
            target-out.zip
      - name: Report the release
        run: |
          echo "Please publish the [draft release](https://github.com/YDX-2147483647/gb7714-bench/releases)." >> "$GITHUB_STEP_SUMMARY"

  check-website:
    # A quick check that does not need run-processors.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - run: pnpm install
        working-directory: website

      - run: pnpm exec biome ci
        working-directory: website
      - run: pnpm typecheck
        working-directory: website

  build-website:
    runs-on: ubuntu-latest
    needs: [run-processors, check-website]
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/download-artifact@v8
        with:
          name: target-out
          path: target/out/

      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - run: pnpm install
        working-directory: website

      - run: pnpm test
        working-directory: website
      - run: pnpm build
        working-directory: website

      - uses: actions/upload-artifact@v7
        with:
          name: website-build-client
          path: website/build/client/

  deploy-netlify:
    runs-on: ubuntu-latest
    needs: build-website
    environment:
      name: deploy-netlify
      url: ${{ steps.netlify-deploy.outputs.deploy_url }}
    steps:
      - uses: actions/checkout@v6
      - run: mkdir -p website/build/
      - uses: actions/download-artifact@v8
        with:
          name: website-build-client
          path: website/build/client/
      - name: Install netlify-cli
        run: npm install -g netlify-cli@^26.1.0
      - name: Run netlify deploy ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
        id: netlify-deploy
        shell: bash
        run: |
          set -euxo pipefail
          netlify deploy \
            --dir website/build/client/ \
            --message "Deployed from $(git describe --dirty --always) (run ${{ github.run_id }} by ${{ github.triggering_actor }} from ${{ github.ref }} in ${{ github.repository }})" \
            ${{ github.ref == 'refs/heads/main' && '--prod' || '' }} \
            --no-build \
            --json \
            --debug | tee netlify-deploy.log
          cat netlify-deploy.log

          deploy_url=$(cat netlify-deploy.log | grep --invert-match '^\[project\.ts\]: detect' | jq .deploy_url --raw-output)
          echo "deploy_url=$deploy_url" >> "$GITHUB_OUTPUT"
        env:
          NETLIFY_SITE_ID: ${{ vars.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
